# Generated by Django 4.1.4 on 2022-12-10 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Equipo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ide", models.IntegerField()),
                ("nombre", models.CharField(max_length=256)),
                ("descripcion", models.CharField(max_length=256)),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("BODEGA", "Bodega"),
                            ("ASIGNADO", "Asignado"),
                            ("MANTENCION", "Mantencion"),
                        ],
                        default="BODEGA",
                        max_length=256,
                    ),
                ),
                ("ubicacion", models.CharField(max_length=256)),
                ("fecha_mantencion", models.DateField()),
                (
                    "condicion",
                    models.CharField(
                        choices=[
                            ("OPERATIVO", "Operativo"),
                            ("INOPERATIVO", "Inoperativo"),
                            ("FALLANDO", "Fallando"),
                        ],
                        default="OPERATIVO",
                        max_length=256,
                    ),
                ),
                ("observaciones", models.DateField(max_length=256)),
            ],
        ),
    ]
