# Generated by Django 4.1.4 on 2022-12-10 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventariado", "0002_alter_equipo_observaciones"),
    ]

    operations = [
        migrations.AlterField(
            model_name="equipo",
            name="observaciones",
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
